# 檢測模型的權重檔案路徑
weights: "D:\\Git\\robotlearning\\yolo_inference_test\\weld_best.pt"


# 運行設備（可以是 'cpu' 或 'cuda'）
device: "cpu"

# 信心閾值，用於篩選模型檢測結果（0 到 1）
conf_thres: 0.60

# IOU 閾值，用於篩選框的重疊程度（0 到 1）
iou_thres: 0.45


# 圖像尺寸（寬度, 高度），用於輸入模型的圖像大小
imgsz: [640, 640]

timeout: 2

iou_thres: 0.45

expected_items:
  - weld_1
  - weld_2
  - weld_3
  - weld_4
  - weld_5
  - weld_6
  - weld_7
  - weld_8

